# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
    - tlmgr init-usertree
    - tlmgr install wasysym
    - tlmgr install ec
    - tlmgr install cm-super
    - tlmgr install yfonts
    - tlmgr install collection-latexrecommended
    - tlmgr install collection-fontsrecommended
    - sudo apt-get install texlive-fonts-recommended
    - sudo apt-get install texlive texlive-latex3
    - sudo apt install texlive-latex-extra
    - tlmgr install bbm
    - tlmgr install bbm-macros
    - sudo apt-get install texlive-fonts-recommended texlive-fonts-extra texlive-latex-recommended
language: R
cache: packages
r_build_args: '--resave-data --compact-vignettes="gs+qpdf"'
