# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
    - tlmgr install bbm
    - tlmgr install bbm-macros
    - tlmgr install collection-fontsrecommended
    - sudo apt-get install texlive-fonts-recommended texlive-fonts-extra texlive-latex-recommended
language: R
cache: packages
r_build_args: '--resave-data --compact-vignettes="gs+qpdf"'
